services:
  - type: web
    name: secure-file-storage
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1

databases:
  - name: mongodb
    databaseName: secure-file-storage
    user: admin